version: "3.7"
services:
  automattic:
    environment:
      AWS_PROFILE: "${AWS_PROFILE}"
      AWS_DEFAULT_REGION: "${AWS_REGION}"
    image: brad
    working_dir: /automattic/terraform
    volumes:
      - type: bind
        source: $HOME/.aws
        target: /root/.aws
        read_only: true
      - type: bind
        source: .
        target: /automattic

